@startuml Интегрированный вариант

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!pragma layout smetana

' Пользователи
Person(operator, "Оператор фермы", "Дежурный сотрудник на месте.\nПолучает алерты и управляет\nкормушками/поилками локально.")
Person(vet, "Зоотехник", "Здоровье стада, анализ инцидентов")
Person(director, "Директор", "Отчеты")
Person(analyst, "Аналитик", "Аналитика, BI")

' Внутренние системы
System(platform, "Платформа мониторинга свиноводства", "Центральный сервер + агенты на фермах")

' Внешние системы
' Существующие
System_Ext(bi, "BI-система (Power BI)", "Отчеты и визуализация")
System_Ext(kafka, "Kafka", "Метрики")
System_Ext(erp, "ERP (1С:Агро)", "Данные о кормах и поголовье")
System_Ext(dwh, "DWH", "Существующее хранилище данных.\nПолучает аналитику для\nисторических отчётов и BI.")
' Новые
System_Ext(iot, "IoT-устройства", "Камеры, кормушки, поилки")
System_Ext(water_filter, "Система фильтрации воды", "")
System_Ext(ml, "ML-модели (партнёрские)", "Анализ видео, детекция инцидентов")
System_Ext(sms, "SMS-шлюз", "Уведомления без интернета")

' Связи
' С пользователями
Rel(operator, platform, "Получает алерты, управляет устройствами", "Мобильное приложение")
Rel(vet, platform, "Анализирует здоровье стада и инциденты")
Rel(director, platform, "Смотрит KPI и отчеты")
Rel(analyst, bi, "Аналитика")
Rel(sms, operator, "Получает алерты")
' С системами
Rel(platform, sms, "Отправляет алерты")
Rel(platform, kafka, "Метрики")
Rel(platform, dwh, "Сохраняет данные", "ETL")
Rel(platform, iot, "Управляет кормушками и поилками")
Rel(platform, ml, "Запрашивает инференс (детекция драк, болезней, подсчёт поголовья)")
Rel(dwh, bi, "Метрики")
Rel(iot, platform, "Передаёт видео и показания датчиков")
Rel(erp, platform, "Предоставляет данные о поголовье и кормах")
Rel(water_filter, platform, "Передаёт данные о состоянии фильтров")

@enduml
